### ISSUE TITLE
Using NodeLinter results in a recursion error.

### ISSUE THREAD

**Issue by zekesonxx** [SublimeLinter/SublimeLinter3#161]
```text
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 58, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 66, in loop
    self.lint(view_id, timestamp)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 112, in lint
    self.callback(view_id, timestamp)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 123, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 917, in lint_view
    linter.lint(hit_time)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1295, in lint
    cmd = self.get_cmd()
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1047, in get_cmd
    return self.build_cmd()
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1079, in build_cmd
    have_path, path = self.context_sensitive_executable_path(cmd)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 59, in context_sensitive_executable_path
    pkgpath = self.find_pkgpath(cwd)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 97, in find_pkgpath
    return self.find_pkgpath(parent)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 97, in find_pkgpath
    return self.find_pkgpath(parent)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 97, in find_pkgpath
    return self.find_pkgpath(parent)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 97, in find_pkgpath
    return self.find_pkgpath(parent)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 97, in find_pkgpath
    return self.find_pkgpath(parent)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 97, in find_pkgpath
    return self.find_pkgpath(parent)
[literally that hundreds of times]
  File "./ntpath.py", line 121, in join
  File "./ntpath.py", line 102, in isabs
  File "./ntpath.py", line 210, in splitdrive
  File "./ntpath.py", line 88, in normcase
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

Just a very basic linter, and with the normal `Linter` class it works fine.

**Comment by malandrew** [comment]
@zekesonxx Can you confirm this is resolved?

**Comment by zekesonxx** [comment]
@malandrew Turns out if you don't solve something for a month it doesn't get solved.

Works just fine now.
