### ISSUE TITLE
Linter-php installing issue

### ISSUE THREAD

**Issue by didineedthis** [SublimeLinter/SublimeLinter3#187]
i have sublimetext 3 installed , i have installed SublimeLinter and then installed the package SublimeLinter-php

For the life of me i can not get it to mark up errors!!. i have php installed via xampp....The php directory is located at C:xampp/php/php.exe

i used the path tool to add my path, i am using windows 8.1 x64

The path tool added my path to C:\Users\steve\AppData\Roaming\npm;C:\xampp\php;

i then added this path inside SublimeLinter

        "paths": {
            "linux": [],
            "osx": [],
            "windows": [
                {
                    "sublimelinter": true,
                    "sublimelinter_executable_map": {
                        "css": "C:/Program Files (x86)/nodejs/node.exe",
                        "javascript": "C:/Program Files (x86)/nodejs/node.exe",
                        "php": "C:/xampp/php"
                    }
                }
            ]
  
this does not work, i tried changing the path to "C:\Users\steve\AppData\Roaming\npm;C:\xampp\php;"
this wont work either , i am at a loss here i have tried adding /php.exe to the end of the path and also to th path in windows but i still cant get it working, i have read every webpage on google and i still cant get it working, any help or advice would be great. Thanks

**Comment by didineedthis** [comment]
i have enabled Debug Mode and loaded the console, this is what was generated, i cant see anything related to Errors or Warning, this is the only line with error in it

TypeError: sequence item 0: expected str instance, dict found

DPI scale: 1
startup, version: 3065 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/steve/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/steve/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 8
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/steve/AppData/Roaming/Sublime Text 3/Installed Packages
found 5 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 5 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 2 orphaned files: 0 total files: 183 cache hits: 181
pre session restore time: 0.070016
startup time: 0.085016
first paint time: 0.086016
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
loaded 837 snippets
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: c:\users\steve\appdata\local\temp\SublimeLinter3-steve 
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 49, in plugin_loaded
    plugin.on_activated(window.active_view())
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 282, in on_activated
    self.check_syntax(view)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 209, in check_syntax
    Linter.assign(view, reset=True)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 723, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1457, in can_lint
    cls.executable_path = cls.which(executable) or ''
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1026, in which
    return util.which(cmd, module=getattr(cls, 'module', None))
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 806, in which
    return find_executable(cmd)
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 1088, in find_executable
    env = create_environment()
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 741, in create_environment
    env['PATH'] = os.pathsep.join(paths) + os.pathsep + env['PATH']
TypeError: sequence item 0: expected str instance, dict found
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
found 5 files for base name Main.sublime-menu
Package Control: Skipping automatic upgrade, last run at 2015-02-07 06:20:03, next run at 2015-02-07 07:20:03 or after
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded

**Comment by skj3gg** [comment]
Seems you have an incorrectly defined path. When you go into the command prompt, do you get a response from entering `where php`

**Comment by didineedthis** [comment]
Thanks for the reply, appreciated.
if i enter the path in a command promt and nothing happens it just goes to a new line

**Comment by skj3gg** [comment]
this means that you're windows `Path` environment variable is not correct.

**Comment by didineedthis** [comment]
yes i thought that too,
but i used the path tool and thats the path the tool gave me, i also entered it manually and still the same result, am at a loose end and cant think of anything else to do

**Comment by skj3gg** [comment]
Not sure what the path tool is, what is your path though? Can you reach anything that you personally added to your path through the `where` command in the CMD?

**Comment by didineedthis** [comment]
Sorry but i am new to all this, how do i use the where command in the command prompt?

**Comment by skj3gg** [comment]
open command prompt (windows key, type `cmd` and press enter when it shows up on the right, in the command prompt type `where [executable]` and hit enter. [executable] being whatever your looking for. In our case `where php`. It should return an absolute path if it finds it.

**Comment by didineedthis** [comment]
if i type "where php" in the cmd promp i gat an error messgage "where is not recognised as an internal or external command operable program or batch file" i am using windows 8.1
regards

**Comment by skj3gg** [comment]
ok, how about in powershell type `get-command php`

**Comment by didineedthis** [comment]
ok i ran it as administrator and it says "C:/xampp/php/php.exe"
i have already tried this location

**Comment by skj3gg** [comment]
what about not as administrator?

**Comment by didineedthis** [comment]
i ran get-command php in powershell and it gave me this message

Application php.exe 
PS C:\Users\Steve>

**Comment by didineedthis** [comment]
"what about not as administrator?"
if i run as not administrator i get same message as above
"if i type "where php" in the cmd promp i gat an error message "where is not recognised as an internal or external command operable program or batch file"

**Comment by skj3gg** [comment]
So I overlooked your preferences. your path setting is wrong. check out: [adding to the path setting](http://sublimelinter.readthedocs.org/en/latest/troubleshooting.html#adding-to-the-paths-setting)

Though if it is in your environment PATH variable. It shouldn't be needed there as well.

**Comment by didineedthis** [comment]
if i navigate to my php folder it is located at C:/xampp/php/php.exe ... what should the path be ? 
i cant get my head round this, i installed it on my mac and it working fine but i need it on my windows 8 pc as that is my work pc, i only use a mac for pleasure

regards

**Comment by skj3gg** [comment]
PATH environment variable should have `C:/xampp/php` in it.

SublimeLinter Preferences path setting should look like this:

```
"paths": {
        "linux": [],
        "osx": [],
        "windows": []
},
```

**Comment by skj3gg** [comment]
Or you could have it vice versa, with it not in your PATH variable and your "path" preferences setting looking like this:

```
"paths": {
        "linux": [],
        "osx": [],
        "windows": [
                "C:/xampp/php/"
        ]
},
```

**Comment by didineedthis** [comment]
thats exactly how i have it setup, cant understand why it wont work

**Comment by skj3gg** [comment]
Can you paste:

1. your path
2. your SL path setting
3. the console debug output after startup and trying to lint a php page with errors.

**Comment by didineedthis** [comment]
User Variable for steve
C:\Users\steve\AppData\Roaming\npm;C:/xampp/php

"linux": [],
            "osx": [],
            "windows": [
                {
                    "sublimelinter": true,
                    "sublimelinter_executable_map": {
                        "css": "c:/Program Files (x86)/nodejs/node.exe",
                        "javascript": "c:/Program Files (x86)/nodejs/node.exe",
                        "php": "C:/xampp/php/"
                    }
                }
            ]




DPI scale: 1
startup, version: 3065 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/steve/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/steve/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 8
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/steve/AppData/Roaming/Sublime Text 3/Installed Packages
found 5 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 5 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 1 orphaned files: 0 total files: 184 cache hits: 183
pre session restore time: 0.0830204
startup time: 0.0980204
first paint time: 0.0990204
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-jshint.linter
loaded 837 snippets
SublimeLinter: jshint linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: c:\users\steve\appdata\local\temp\SublimeLinter3-steve 
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 49, in plugin_loaded
    plugin.on_activated(window.active_view())
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 282, in on_activated
    self.check_syntax(view)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 209, in check_syntax
    Linter.assign(view, reset=True)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 723, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1457, in can_lint
    cls.executable_path = cls.which(executable) or ''
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1026, in which
    return util.which(cmd, module=getattr(cls, 'module', None))
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 806, in which
    return find_executable(cmd)
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 1088, in find_executable
    env = create_environment()
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 741, in create_environment
    env['PATH'] = os.pathsep.join(paths) + os.pathsep + env['PATH']
TypeError: sequence item 0: expected str instance, dict found
Writing file /C/Users/steve/AppData/Roaming/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings with encoding UTF-8 (atomic)
+ Info: processing `HTML': please wait...
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
Could not import subprocess32 module, falling back to subprocess module
found 5 files for base name Main.sublime-menu
reloading Packages/User/SublimeLinter.sublime-settings
Package Control: Skipping automatic upgrade, last run at 2015-02-08 17:42:55, next run at 2015-02-08 18:42:55 or after
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 282, in on_activated
    self.check_syntax(view)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 209, in check_syntax
    Linter.assign(view, reset=True)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 723, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1457, in can_lint
    cls.executable_path = cls.which(executable) or ''
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1026, in which
    return util.which(cmd, module=getattr(cls, 'module', None))
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 806, in which
    return find_executable(cmd)
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 1088, in find_executable
    env = create_environment()
  File "./functools.py", line 251, in wrapper
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 741, in create_environment
    env['PATH'] = os.pathsep.join(paths) + os.pathsep + env['PATH']
TypeError: sequence item 0: expected str instance, dict found
current triggername: 'php-complete-variables'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1825, in is_enabled
    return super(SublimecodeintelDisableLiveCommand, self).is_enabled(True, False)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1803, in is_enabled
    enabled = super(SublimecodeintelLiveCommand, self).is_enabled(True)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1835, in is_enabled
    return super(SublimecodeintelDisableLiveLangCommand, self).is_enabled(True, True)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1803, in is_enabled
    enabled = super(SublimecodeintelLiveCommand, self).is_enabled(True)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1793, in is_enabled
    return super(SublimecodeintelDisableCommand, self).is_enabled(True)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1820, in is_enabled
    return super(SublimecodeintelEnableLiveCommand, self).is_enabled(False, False)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1803, in is_enabled
    enabled = super(SublimecodeintelLiveCommand, self).is_enabled(True)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1830, in is_enabled
    return super(SublimecodeintelEnableLiveLangCommand, self).is_enabled(False, True)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1803, in is_enabled
    enabled = super(SublimecodeintelLiveCommand, self).is_enabled(True)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1788, in is_enabled
    return super(SublimecodeintelEnableCommand, self).is_enabled(False)
  File "C:\Users\steve\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given

**Comment by skj3gg** [comment]
Your path preferences doesn't look like what I said.

**Comment by didineedthis** [comment]
i have removed C:\Users\steve\AppData\Roaming\npm;C:/xampp/php```
and entered C:/xampp/php

still not working
regards

**Comment by skj3gg** [comment]
I don't feel I can help you unless you follow my instructions. You are editing your Windows environment variables when that's not what I said to do. Please open you SublimeLinter User Packages Settings and in then make your path variable look exactly like this:

```
"paths": {
            "linux": [],
            "osx": [],
            "windows": ["C:/xampp/php"]
},
```

it currently looks like this:

```
"paths": {
        "linux": [],
        "osx": [],
        "windows": [
            {
                "sublimelinter": true,
                "sublimelinter_executable_map": {
                    "css": "C:/Program Files (x86)/nodejs/node.exe",
                    "javascript": "C:/Program Files (x86)/nodejs/node.exe",
                    "php": "C:/xampp/php"
                }
            }
        ]
},
```

**Comment by didineedthis** [comment]
sorry i have tried what you said and it never worked

**Comment by didineedthis** [comment]
i just got it working, i removed this code
                {
                    "sublimelinter": true,
                    "sublimelinter_executable_map": {
                        "css": "c:/Program Files (x86)/nodejs/node.exe",
                        "javascript": "c:/Program Files (x86)/nodejs/node.exe",
                        "php": "C:/xampp/php/"
                    }
                }

and put C:/xampp/php in my windows variable, will this cause problems?

**Comment by skj3gg** [comment]
https://github.com/SublimeLinter/SublimeLinter3/issues/187#issuecomment-73421513

I gave you that answer earlier. No it will not cause problems.
