### ISSUE TITLE
XML or text declaration not at start of entity

### ISSUE THREAD

**Issue by binarykitchen** [SublimeLinter/SublimeLinter3#192]
Seeing this error

```
Traceback (most recent call last):
  File "/home/michael-heuberger/.config/sublime-text-3/Packages/SublimeLinter/lint/util.py", line 262, in generate_color_scheme_async
    plist = ElementTree.XML(scheme_text)
  File "./xml/etree/ElementTree.py", line 1356, in XML
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 13, column 0
```

Any ideas why? I just installed it and did not edit any preferences.

**Comment by skj3gg** [comment]
What does your SublimeText user settings look like? Also OS?
Seems to be a problem when SL tries to add its colors to your color scheme.

**Comment by binarykitchen** [comment]
On Ubuntu 14.10 here.

These are my settings:

```
{
	"bold_folder_labels": true,
	"caret_style": "wide",
	"color_scheme": "Packages/Dracula Color Scheme/Dracula.tmTheme",
	"create_window_at_startup": false,
	"draw_minimap_border": true,
	"draw_white_space": "all",
	"ensure_newline_at_eof_on_save": true,
	"folder_exclude_patterns":
	[
		".svn",
		".git",
		".hg",
		"CVS",
		".idea"
	],
	"font_size": 11,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"rulers":
	[
		110
	],
	"save_on_focus_lost": true,
	"shift_tab_unindent": true,
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true
}
```

**Comment by skj3gg** [comment]
I was able to replicate this, Like previously thought seems to be a problem with [zenorocha/dracula-theme](https://github.com/zenorocha/dracula-theme) not being a valid xml document. Will look into further, but probably will fix it copyright comment is put after xml declaration.

**Comment by skj3gg** [comment]
This was fixed in Dracula, as soon as it is released you should have the changes.

**Comment by binarykitchen** [comment]
ths

**Comment by zenorocha** [comment]
Released: https://github.com/zenorocha/dracula-theme/releases/tag/v0.7.5
