### ISSUE TITLE
Startup errors in one of projects.

### ISSUE THREAD

**Issue by max-mykhailenko** [SublimeLinter/SublimeLinter3#202]
I have two project with the same linter configuration, but only in one project I have bug:
```
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/t6/pllpprps447gwgwh5mbghtqw0000gn/T/SublimeLinter3-max 
Traceback (most recent call last):
  File "./json/decoder.py", line 242, in JSONArray
  File "./json/scanner.py", line 63, in _scan_once
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "/Users/max/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 49, in plugin_loaded
    plugin.on_activated(window.active_view())
  File "/Users/max/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 282, in on_activated
    self.check_syntax(view)
  File "/Users/max/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 209, in check_syntax
    Linter.assign(view, reset=True)
  File "/Users/max/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 744, in assign
    linter = linter_class(view, syntax)
  File "/Users/max/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 55, in __init__
    self.read_manifest(path.getmtime(self.manifest_path))
  File "/Users/max/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 226, in read_manifest
    self.cached_manifest = json.load(open(self.manifest_path))
  File "./json/__init__.py", line 274, in load
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 368, in raw_decode
  File "./json/scanner.py", line 40, in _scan_once
  File "./json/decoder.py", line 244, in JSONArray
ValueError: Expecting object: line 1 column 2 (char 1)
SublimeLinter: found existing HTML syntax, version 3 
Emmet: No need to update PyV8
SublimeLinter: found existing Rails syntax, version 1 
Package Control: Skipping automatic upgrade, last run at 2015-02-23 10:25:44, next run at 2015-02-23 11:25:44 or after
```
Sublime Linter, sublime linter eslint, OSX 10.10.2

**Comment by max-mykhailenko** [comment]
Find file with bug, but if I copy all content to the new view, validation works right!

**Comment by skj3gg** [comment]
Glad you figured it out! This issue is resolved, right?

**Comment by max-mykhailenko** [comment]
One question left: why linter try to parse `package.json` in parent folder?

**Comment by skj3gg** [comment]
It is part of the [NodeLInter](https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/node_linter.py) class, it a feature that allows the linter executable called to be in the local `node_modules` directory instead of installed globally.
