### ISSUE TITLE
mainfest || package.json is read as ASCII

### ISSUE THREAD

**Issue by einarlove** [SublimeLinter/SublimeLinter3#208]
Package.json is read by SublimeLinter as ASCII not UTF-8, so the author which contained ```ö``` broke the whole plugin.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "/Users/einarlove/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 282, in on_activated
    self.check_syntax(view)
  File "/Users/einarlove/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 209, in check_syntax
    Linter.assign(view, reset=True)
  File "/Users/einarlove/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 744, in assign
    linter = linter_class(view, syntax)
  File "/Users/einarlove/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 55, in __init__
    self.read_manifest(path.getmtime(self.manifest_path))
  File "/Users/einarlove/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 225, in read_manifest
    self.cached_manifest_hash = self.hash_manifest()
  File "/Users/einarlove/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 232, in hash_manifest
    return hashlib.sha1(f.read().encode('utf-8')).hexdigest()
  File "./encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 347: ordinal not in range(128)
```

**Comment by skj3gg** [comment]
@malandrew, know any reason behind [node_linter.py#L232](https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/node_linter.py#L232) and why it has the `.encode('utf-8)`.

I believe that file is already being opened in utf-8 encoding by default, so the double encoding attempt is throwing the final error.

**Comment by malandrew** [comment]
I don't recall why, but if I were to guess it is because I'm used to opening stuff up as Buffers from my work with nodejs and add 'utf8' by default when I want text. I would imagine that that can be safely removed, but someone who knows python better than me should make that judgement.

**Comment by skj3gg** [comment]
Thanks for bringing this to our attention @einarlove

Your issue worked for me after being removed, so that has been released and should be seen in Package Control in 30 minutes or so. Thanks to @malandrew for providing the history.

**Comment by skj3gg** [comment]
or not.

**Comment by skj3gg** [comment]
Sorry, carry this on in #209
