### ISSUE TITLE
SublimeLinter 3.4.35 - TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by Flet** [SublimeLinter/SublimeLinter3#209]
I think this commit caused it: https://github.com/SublimeLinter/SublimeLinter3/commit/0d26f7b0abf83c5037e48e1d2ddd5d2cfe7f8458

```
reloading plugin SublimeLinter-contrib-standard.linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /home/icmpdev/.config/sublime-text-3/Installed Packages/SublimeLinter-contrib-standard.sublime-package", line 16, in <module>
  File "/home/icmpdev/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 127, in __init__
    persist.register_linter(cls, name, attrs)
  File "/home/icmpdev/.config/sublime-text-3/Packages/SublimeLinter/lint/persist.py", line 462, in register_linter
    linter.Linter.assign(view, linter_name=linter_name)
  File "/home/icmpdev/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 744, in assign
    linter = linter_class(view, syntax)
  File "/home/icmpdev/.config/sublime-text-3/Packages/SublimeLinter/lint/node_linter.py", line 55, in __init__
    self.read_manifest(path.getmtime(self.manifest_path))
  File "/home/icmpdev/.config/sublime-text-3/Packages/SublimeLinter/lint/node_linter.py", line 225, in read_manifest
    self.cached_manifest_hash = self.hash_manifest()
  File "/home/icmpdev/.config/sublime-text-3/Packages/SublimeLinter/lint/node_linter.py", line 232, in hash_manifest
    return hashlib.sha1(f.read()).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by feross** [comment]
+1

**Comment by skj3gg** [comment]
Really sorry! New release is out and waiting for Package Control.

**Comment by Flet** [comment]
Thanks, this was fixed by the new release!
