### ISSUE TITLE
SublimeLinter error for package.json without name attribute 

### ISSUE THREAD

**Issue by erlethor** [SublimeLinter/SublimeLinter3#213]
SublimeLinter gave crashes with an error (see below) if there is no "name" attribute in the package.json. This is of course a bad package.json if it has no name. However this shouldn't stop the linter from running. The error happens in 
Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 89
`is_dep = True if self.npm_name == pkg['name'] else False`

I don't know python but there should be a check for existance of the attribute "name" before accessing it. In javascript it would be something like `typeof pkg.name !== "undefined"`

Regards,
Thorsten
```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 58, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 66, in loop
    self.lint(view_id, timestamp)
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 112, in lint
    self.callback(view_id, timestamp)
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 123, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 917, in lint_view
    linter.lint(hit_time)
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 64, in lint
    is_dep = self.is_dependency()
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 89, in is_dependency
    is_dep = True if self.npm_name == pkg['name'] else False
KeyError: 'name'
 ```

**Comment by skj3gg** [comment]
Fixed and released with #215
