### ISSUE TITLE
Traceback when handling lint error

### ISSUE THREAD

**Issue by rikhul** [SublimeLinter/SublimeLinter3#241]
I get this trace when linting

``` python
SublimeLinter: Traceback (most recent call last):
  File "/home/rikardh/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 58, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rikardh/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 66, in loop
    self.lint(view_id, timestamp)
  File "/home/rikardh/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 112, in lint
    self.callback(view_id, timestamp)
  File "/home/rikardh/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 123, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/home/rikardh/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 903, in lint_view
    if fnmatch(filename, pattern):
  File "./fnmatch.py", line 35, in fnmatch
  File "./posixpath.py", line 54, in normcase
TypeError: normcase() argument must be str or bytes, not 'int'
```

ubuntu 14.04
sublimelinter 3.4.39
flake8 2.4.0

**Comment by groteworld** [comment]
I'm really sorry, last spring/summer I was in a conference circuit and I missed a lot of these issues being busy. So first I want to apologise, for really dropping the ball, and leaving you hanging.

So most likely this issue happened because in your SL-flake8 setting `exclude` is contains an `int` in its array instead of a string. This must

Incorrect Example
```
"flake8": {
                "excludes": [208],
            },
```

Correct Example
```
"flake8": {
                "excludes": ["208"],
            },
```

Hopefully this helps you, or you figured out your issue.

Sorry again!

**Comment by braver** [comment]
If this is still an issue let me know, but let's be optimistic and close this one ;)
