### ISSUE TITLE
SL3 does work with pep8 1.6.2

### ISSUE THREAD

**Issue by zhuzelong** [SublimeLinter/SublimeLinter3#260]
I updated pep8 to 1.6.2 via pip and then SL3 fails to lint.

The error message:

```
SublimeLinter: WARNING: import of flake8.engine module in flake8 failed, linter will not work with python 3 code 
SublimeLinter: WARNING: no flake8 version could be extracted from:
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/flake8/main.py", line 24, in main
    flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)
  File "/usr/local/lib/python2.7/site-packages/flake8/engine.py", line 110, in get_style_guide
    kwargs['parser'], options_hooks = get_parser()
  File "/usr/local/lib/python2.7/site-packages/flake8/engine.py", line 48, in get_parser
    (extensions, parser_hooks, options_hooks, ignored) = _register_extensions()
  File "/usr/local/lib/python2.7/site-packages/flake8/engine.py", line 32, in _register_extensions
    checker = entry.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2344, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 838, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pep8 1.6.2 (/usr/local/lib/python2.7/site-packages), Requirement.parse('pep8<1.6,>=1.5.7'))
```

**Comment by jawshooah** [comment]
This is an issue with SublimeLinter-pep8, not SL3 proper.

Please report [linter-specific issues](https://github.com/SublimeLinter/SublimeLinter3/blob/master/CONTRIBUTING.md) on their respective [repositories](https://github.com/SublimeLinter/SublimeLinter-pep8).
