### ISSUE TITLE
PEP8 Version Conflict with pep8 1.6.2 (current version)

### ISSUE THREAD

**Issue by utkonos** [SublimeLinter/SublimeLinter3#321]
I'm getting the following error when starting sublime text 3:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 34, in plugin_loaded
    linter.initialize()
  File "linter in /Users/username/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-flake8.sublime-package", line 92, in initialize
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pep8 1.6.2 (/usr/local/lib/python3.4/site-packages), Requirement.parse('pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7'))
SublimeLinter: pyflakes activated: <builtin> (disabled in settings) 
SublimeLinter: pep257 activated: <builtin> 
SublimeLinter: flake8 activated: <builtin> 
SublimeLinter: ERROR: could not launch ['<builtin>', 'pep8', '--version'] 
SublimeLinter: reason: [Errno 2] No such file or directory: '<builtin>' 
SublimeLinter: PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin 
SublimeLinter: WARNING: no pep8 version could be extracted from:
```

**Comment by jawshooah** [comment]
This is a requirement of [flake8](https://gitlab.com/pycqa/flake8), and has nothing to do with us.

See [this StackOverflow answer](http://stackoverflow.com/a/29340700/1500244) for a potential solution.
