### ISSUE TITLE
Linters will not activate! Linter deactivated, cannot locate file

### ISSUE THREAD

**Issue by newCodez99** [SublimeLinter/SublimeLinter3#349]
My linters are not working. I have spent the last few days reading the docs and other sites to get these working with no love. I was able to get the linters working randomly a few times but after restarting the program they continue to give me errors.

I am on win 7
My paths are set 

```
C:\Users\BigBoy>where tidy
C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\tidy.exe
C:\Users\BigBoy\AppData\Roaming\npm\tidy.exe

C:\Users\BigBoy>where csslint
C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\csslint
C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\csslint.cmd
C:\Users\BigBoy\AppData\Roaming\npm\csslint
C:\Users\BigBoy\AppData\Roaming\npm\csslint.cmd

C:\Users\BigBoy>path
PATH=C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;
C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files\nodejs\;C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64;C:\
Users\BigBoy\AppData\Roaming\npm;C:\cygwin64\home\BigBoy;C:\cygwin64;
```

I made extra paths in a few attempts over the last few days, I dont think its causing problems.

Here is my settings file. Is everything good here? There was a lot of mixed info on path syntax, some say 2 \slashes and some use normal, single /slashes. I was not able to find a windows example in the docs.

```
{
    "default": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": [
                "C:\\Users\\BigBoy\\Desktop\\Sublime Text Build 3083 x64\\",
            ]
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "python django": "python",
            "html 5": "html",
            "html (django)": "html",
            "html (rails)": "html",
            "javascript (babel)": "javascript",
            "php": "html"
        },
        "warning_color": "DDB700",
        "wrap_find": true,
    }
}
```

Debug

```
DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Users/BigBoy/Desktop/Sublime Text Build 3083 x64/sublime_text.exe
working dir: /C/Users/BigBoy/Desktop/Sublime Text Build 3083 x64
packages path: /C/Users/BigBoy/Desktop/Sublime Text Build 3083 x64/Data/Packages
state path: /C/Users/BigBoy/Desktop/Sublime Text Build 3083 x64/Data/Local
zip path: /C/Users/BigBoy/Desktop/Sublime Text Build 3083 x64/Packages
zip path: /C/Users/BigBoy/Desktop/Sublime Text Build 3083 x64/Data/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.155471
loading dictionary Packages/Language - English/en_US.dic
warning: mnemonic t not found in menu caption Tools
startup time: 0.209471
first paint time: 0.233471
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin All Autocomplete.all_views_completions
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin Better Completion.main
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin Colorcoder.colorcoder
reloading plugin Emmet.emmet-plugin
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin memTask.memTask
reloading plugin memTask.ordereddict
reloading plugin Origami.origami
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarFolders.SideBarFolders
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: htmltidy linter loaded 
reloading plugin View In Browser.ViewInBrowserCommand
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin ColorPicker.sublimecp
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin JSHint.JSHint
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
Traceback (most recent call last):
  File "C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "bh_core in C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\Data\Installed Packages\BracketHighlighter.sublime-package", line 884, in on_selection_modified
  File "bh_core in C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\Data\Installed Packages\BracketHighlighter.sublime-package", line 903, in ignore_event
AttributeError: 'NoneType' object has no attribute 'ignore_all'
Traceback (most recent call last):
  File "C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "bh_core in C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\Data\Installed Packages\BracketHighlighter.sublime-package", line 884, in on_selection_modified
  File "bh_core in C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\Data\Installed Packages\BracketHighlighter.sublime-package", line 903, in ignore_event
AttributeError: 'NoneType' object has no attribute 'ignore_all'
Traceback (most recent call last):
  File "C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "bh_core in C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\Data\Installed Packages\BracketHighlighter.sublime-package", line 884, in on_selection_modified
  File "bh_core in C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\Data\Installed Packages\BracketHighlighter.sublime-package", line 903, in ignore_event
AttributeError: 'NoneType' object has no attribute 'ignore_all'
Traceback (most recent call last):
  File "C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "bh_core in C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\Data\Installed Packages\BracketHighlighter.sublime-package", line 884, in on_selection_modified
  File "bh_core in C:\Users\BigBoy\Desktop\Sublime Text Build 3083 x64\Data\Installed Packages\BracketHighlighter.sublime-package", line 903, in ignore_event
AttributeError: 'NoneType' object has no attribute 'ignore_all'
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: c:\users\bigboy\appdata\local\temp\SublimeLinter3-BigBoy 
SublimeLinter: WARNING: htmltidy deactivated, cannot locate 'tidy' 
SublimeLinter: WARNING: csslint deactivated, cannot locate 'csslint' 
Emmet: No need to update PyV8
warning: mnemonic t not found in menu caption Tools
warning: mnemonic t not found in menu caption Tools
Package Control: Skipping automatic upgrade, last run at 2015-10-16 12:41:38, next run at 2015-10-16 13:41:38 or after
```

Currently i only have csslint and htmltidy of the sublinters installed. Any ideas on what im missing to get these working?

Thanks.

**Comment by newCodez99** [comment]
My linters started working randomly again. Here is some more code it spit out.

>SublimeLinter: chdir not set or invalid, using E:\finaldraftwebcraft\css 
>SublimeLinter: csslint: illustrator.css ['C:\\Users\\BigBoy\\Desktop\\Sublime Text Build 3083 >x64\\csslint.cmd', '--format=compact'] 

is the chdir causing the problems im having with the linters?

**Comment by auz9** [comment]
Hi,

Hope this issue doesn't bother you anymore.

chdir is not the cause. Took me a while to get comfortable with that message. 
The message will appear whenever no project is opened or some errors in the "chdir" setting in _User/SublimeLinter.sublime-settings_ file.
ST3 simply assumes the folder of the current file.

**Comment by auz9** [comment]
In case you have not seen this, SL-html-tidy do cause ST3 to loose track of system paths [SublimeLinter-html-tidy make the paths configuration not work](https://github.com/SublimeLinter/SublimeLinter-html-tidy/issues/33)

**Comment by auz9** [comment]
You are also editing the default file for SL settings.  There is another _**user**_ file for SL settings.
Usually I copy everything I need from the default to the user's and then make any changes in the user settings. 
The user settings starts with "user" like (https://github.com/SublimeLinter/SublimeLinter-html-tidy/issues/33#issuecomment-113002122

**Comment by braver** [comment]
So, I probably don't understand everything that's said here, but it really seems like a pretty specific setup issue rather than something wrong with SL. If I'm wrong let me know with some explanation and we'll re-open.
