### ISSUE TITLE
RuntimeError: super(): empty __class__ cell

### ISSUE THREAD

**Issue by MichielDeMey** [SublimeLinter/SublimeLinter3#370]
Trying to lint a file renders the following error:

I have two linters installed for JavaScript, `jshint` and `eslint`.
Any ideas?

```
SublimeLinter: -------------------- 
SublimeLinter: chdir not set or invalid, using /Users/michiel/Documents/storied/repos/discovery-server 
SublimeLinter: eslint: server.js ['/usr/local/bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__'] 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/michiel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 58, in loop
    except Empty:
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/michiel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 66, in loop
  File "/Users/michiel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 112, in lint
  File "/Users/michiel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/michiel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 919, in lint_view
    continue
  File "/Users/michiel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 78, in lint
  File "/Users/michiel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1379, in lint
  File "/Users/michiel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1785, in run
    return self.tmpfile(cmd, code)
  File "/Users/michiel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-eslint/linter.py", line 96, in communicate
    return super().communicate(cmd, code)
RuntimeError: super(): empty __class__ cell
```

**Comment by grotewold** [comment]
While I'm confused on what caused the issue. I'm glad to hear it's working for you again!
