### ISSUE TITLE
Linter throws an error in queue.py followed by AttributeError: 'list' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by chokden** [SublimeLinter/SublimeLinter3#396]
I just happen to install Sublimelinter on my ST3, Sublimelinter-ruby and Sublimlinter-rubocop but i cant seem to have the package running. The console shows the following error. 
```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/Dickyi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Dickyi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/Dickyi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/Dickyi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/Dickyi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 924, in lint_view
    linter.lint(hit_time)
  File "/Users/Dickyi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1367, in lint
    cmd = self.get_cmd()
  File "/Users/Dickyi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1119, in get_cmd
    return self.build_cmd()
  File "/Users/Dickyi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1169, in build_cmd
    cmd[0:1] = util.convert_type(os.path.abspath(path), [])
  File "./posixpath.py", line 379, in abspath
  File "./posixpath.py", line 64, in isabs
AttributeError: 'list' object has no attribute 'startswith'
 
SublimeLinter: -------------------- 
```
here is my user setting file. 

```
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "rubocop": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "ruby": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}```

**Comment by imechemi** [comment]
Thanks for raising this, I am getting the same error. Tried several hours looking into existing issues and troubleshooting guides.

**Comment by grotewold** [comment]
this seems related to #395, can you follow my request as well and see if the newest commit fixes your issue before I release it. Thanks!

**Comment by grotewold** [comment]
Further discussion consolidated into #395

**Comment by chokden** [comment]
@grotewold Big thanks for you,  that fixed the problem.
