### ISSUE TITLE
Long list of errors from SublimeLinter-ghc causes SublimeLinter to break

### ISSUE THREAD

**Issue by FPtje** [SublimeLinter/SublimeLinter3#442]
So I'm working on a huge refactor in a large Haskell project and decided to change a data type that was used literally everywhere around the program. `ghc -Wall` gives the warnings of all related files, and SublimeLinter-ghc should pick the ones for the currently open file. However, I think the amount of errors may be too much for SublimeLinter to handle:

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: ghc: Type.hs ['/usr/bin/ghc', '-fno-code', '-Wall', '-Wwarn', '-fno-helpful-errors', '-i.', '-i..', '-i../..', '-i../../..', '-i../../../..', '-i/home/falco/Documents/thesis/elm-compiler/dist/build/autogen', '-package-db=/home/falco/Documents/thesis/cabalsandbox/x86_64-linux-ghc-7.10.3-packages.conf.d'] 
SublimeLinter: ghc output:

<HUGE LIST OF HASKELL ERRORS>

SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 924, in lint_view
    linter.lint(hit_time)
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1453, in lint
    start, end = self.highlight.full_line(line)
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/lint/highlight.py", line 200, in full_line
    start = self.newlines[line] + char_offset
IndexError: list index out of range
```

I'm reporting it here and not in SublimeLinter-ghc because that specific linter is mentioned nowhere in the error. My ghc linter settings are as follows:

```
"linters": {
            "ghc": {
                "@disable": false,
                "args": [
                    "-i.",
                    "-i..",
                    "-i../..",
                    "-i../../..",
                    "-i../../../..",
                    "-i/home/falco/Documents/thesis/elm-compiler/dist/build/autogen",
                    "-package-db=/home/falco/Documents/thesis/cabalsandbox/x86_64-linux-ghc-7.10.3-packages.conf.d"
                ],
                "excludes": []
            },
```

The reason for those parameters is this issue:
https://github.com/SublimeLinter/SublimeLinter-ghc/issues/5

I cannot try to remove those parameters, since that would break linting in the first place.

**Comment by FPtje** [comment]
Also, I just got this error:

```
  File "/opt/sublime_text_3/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/opt/sublime_text_3/sublime_plugin.py", line 288, in <lambda>
    run_callback('on_post_save', callback, lambda: callback.on_post_save(v))
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 441, in on_post_save
    self.file_was_saved(view)
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 445, in file_was_saved
    syntax_changed = self.check_syntax(view)
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 205, in check_syntax
    Linter.assign(view, reset=True)
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 729, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./functools.py", line 251, in wrapper
  File "/home/falco/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1589, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
UnboundLocalError: local variable 'executable' referenced before assignment
```

**Comment by braver** [comment]
(removed the `referenced before assignment ` report, see #491)

**Comment by braver** [comment]
Could you perhaps reproduce this on recent versions of Sublime Text 3 and SublimeLinter?

**Comment by FPtje** [comment]
I haven't seen this in a quite a while. It's probably fixed.
