### ISSUE TITLE
dead plugin

### ISSUE THREAD

**Issue by mmclau14** [SublimeLinter/SublimeLinter3#501]
getting the following traceback on save. little dots are not showing up in gutter, no errors are being caught and displayed
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in <lambda>
    run_callback('on_post_save', callback, lambda: callback.on_post_save(v))
  File "compile_selected_es6 in /Users/michaelmclaughlin/Library/Application Support/Sublime Text 3/Installed Packages/Compile Selected ES6.sublime-package", line 104, in on_post_save
  File "compile_selected_es6 in /Users/michaelmclaughlin/Library/Application Support/Sublime Text 3/Installed Packages/Compile Selected ES6.sublime-package", line 47, in compile
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'babel'
```

**Comment by noma4i** [comment]
According to the trace you are using dead plugin: https://packagecontrol.io/packages/Compile%20Selected%20ES6

Remove it and be happy ;)

**Comment by groteworld** [comment]
Additionally, I don't see anything here that has to do with SublimeLinter. Because of these reasons, until we have more information, there is nothing we can do. Im closing this issue, and I'm sorry for the inconvenience.
