### ISSUE TITLE
error in SublimeLinter daemon

### ISSUE THREAD

**Issue by sabver** [SublimeLinter/SublimeLinter3#546]
Hello,my sublime3 installed the plus-in of stylelint,when I begin use stylelint ,the console show the error:

SublimeLinter: -------------------- 
reloading settings Packages/User/Stylefmt.sublime-settings
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 929, in lint_view
    linter.lint(hit_time)
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 77, in lint
    super(NodeLinter, self).lint(hit_time)
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1410, in lint
    for match, line, col, error, warning, message, near in self.find_errors(output):
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/linter.py", line 75, in find_errors
    type = warning['severity']
KeyError: 'severity'
 
SublimeLinter: -------------------- 
reloading settings Packages/User/Stylefmt.sublime-settings
reloading settings Packages/User/Stylefmt.sublime-settings
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 929, in lint_view
    linter.lint(hit_time)
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 77, in lint
    super(NodeLinter, self).lint(hit_time)
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1410, in lint
    for match, line, col, error, warning, message, near in self.find_errors(output):
  File "/Users/yejianfeng/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/linter.py", line 75, in find_errors
    type = warning['severity']
KeyError: 'severity'
 
SublimeLinter: --------------------

**Comment by GersonRosales** [comment]
Try combine this configuration in your SublimeLinter.sublime-settings

```{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "jscs": {
                "@disable": true,
                "args": [],
                "excludes": []
            },
            "jshint": {
                "@disable": true,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": true,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": true,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "php": "html",
        },
        "tooltip_fontsize": "1rem",
        "tooltip_theme": "Packages/SublimeLinter/tooltip-themes/Default/Default.tooltip-theme",
        "tooltip_theme_excludes": [],
        "tooltips": false,
        "warning_color": "DDB700",
        "wrap_find": true
    }
}```

**Comment by braver** [comment]
There must be a configuration error somewhere, please try again, clean-slate the thing etc. If it persists, please let me know.
