### ISSUE TITLE
dev Build 3128 with fish shell broke linter

### ISSUE THREAD

**Issue by publicarray** [SublimeLinter/SublimeLinter3#567]
```log
startup, version: 3128 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/seb/Library/Application Support/Sublime Text 3/Packages
state path: /Users/seb/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/seb/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.89086
loading dictionary Packages/Language - English/en_GB.dic
startup time: 0.978272
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
[...]
SublimeLinter: scss linter loaded 
reloading plugin SublimeLinter-contrib-write-good.linter
SublimeLinter: writegood linter loaded 
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: htmltidy linter loaded 
reloading plugin SublimeLinter-javac.linter
SublimeLinter: javac linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin SublimeLinter-shellcheck.linter
SublimeLinter: shellcheck linter loaded 
[...]
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/hn/l_73jc515jn1k9jt9crgrcfr0000gn/T/SublimeLinter3-seb 
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "/Users/seb/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 35, in plugin_loaded
    linter.initialize()
  File "/Users/seb/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/ruby_linter.py", line 48, in initialize
    cls.executable_path = cls.lookup_executables(cls.cmd)
  File "/Users/seb/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/ruby_linter.py", line 139, in lookup_executables
    gem_home = util.get_environment_variable('GEM_HOME')
  File "./python3.3/functools.py", line 251, in wrapper
  File "/Users/seb/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 577, in get_environment_variable
    value = out.decode().split('__SUBL_VAR__', 2)[1].strip() or None
IndexError: list index out of range
SublimeLinter: php activated: /usr/local/bin/php 
Emmet: No need to update PyV8
environment variables loaded using: /usr/local/bin/fish -l
Package Control: No updated packages
```

**Comment by braver** [comment]
@publicarray I use SL with the fish as my login shell too, no issues here. Can you check again with the 3.0 release and report back?

**Comment by publicarray** [comment]
@braver Hm, I have since fixed it by cleaned out all sublime preferences and plugins and started adding a few back again. I assume that either I had a wrong preference or a bad plugin was the course of the issue. Thanks for looking into this anyway.
