### ISSUE TITLE
SublimeLinter deamon crashes on fast view changes

### ISSUE THREAD

**Issue by deathaxe** [SublimeLinter/SublimeLinter3#570]
Sometimes if views change too quickly, SublimeLinter tries to access view objects, which do no longer exist. This results in a crash with the attached console output. From this time on most other plugins won't work anymore until ST is restarted.

I am running ST 3126 / 3129 on Windows 10 1703 x64 with latest SublimeLinter (3.8.0)

#### Console output

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\linter.py", line 962, in lint_view
    callback(cls.get_view(vid), linters, hit_time)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\sublimelinter.py", line 138, in highlight
    vid = view.id()
AttributeError: 'NoneType' object has no attribute 'id'
 
SublimeLinter: -------------------- 
```

Maybe a check for valid view object before line 138 could resolve the issue?

```
        if not view:
            return
```

**Comment by alanhoff** [comment]
I'm having the same problem here:

```
startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/alanhoff/Library/Application Support/Sublime Text 3/Packages
state path: /Users/alanhoff/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/alanhoff/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.948031
using gpu buffer for window
loading dictionary Packages/Language - English/en_US.dic
first paint time: 1.03487
startup time: 1.03609
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin All Autocomplete.all_views_completions
reloading plugin API Blueprint.APIBlueprint
reloading plugin API Blueprint.linter
SublimeLinter: apiblueprint linter loaded 
reloading plugin Asciidoctor.commands
reloading plugin Asciidoctor.completions
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin Better CoffeeScript.CoffeeScript
reloading plugin Dictionaries.Dictionaries
reloading plugin DocBlockr.jsdocs
reloading plugin EditorConfig.EditorConfig
reloading plugin Emmet.emmet-plugin
reloading plugin Find++.DirectoryPanel
reloading plugin Find++.FindPlusPlus
reloading plugin Generate Password.password
reloading plugin GenerateUUID.generate_uuid
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_gutter_jump_to_changes
reloading plugin GitGutter.git_gutter_popup
reloading plugin GitGutter.git_gutter_settings
reloading plugin GitGutter.git_gutter_show_diff
reloading plugin HexViewer.hex_checksum
Hex Viewer: md2 hash is not available!
reloading plugin HexViewer.hex_common
reloading plugin HexViewer.hex_editor
reloading plugin HexViewer.hex_finder
reloading plugin HexViewer.hex_highlighter
reloading plugin HexViewer.hex_inspector
reloading plugin HexViewer.hex_notify
reloading plugin HexViewer.hex_viewer
reloading plugin HexViewer.hex_writer
reloading plugin HexViewer.sum_hashes
reloading plugin HexViewer.support
reloading plugin HexViewer.tiger
reloading plugin HexViewer.whirlpool
reloading plugin LoremGibson.Loremgibson
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Rust Enhanced.SyntaxCheckPlugin
reloading plugin Rust Enhanced.toggle_setting
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.Stats
reloading plugin SublimeLinter-contrib-elixirc.linter
SublimeLinter: elixirc linter loaded 
reloading plugin SublimeLinter-contrib-standard.linter
SublimeLinter: standard linter loaded 
reloading plugin SublimeLinter-pyflakes.linter
SublimeLinter: pyflakes linter loaded 
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin anaconda_rust.anaconda_rust
reloading plugin anaconda_rust.plugin_version
reloading plugin Babel.Babel
reloading plugin Floobits.floobits
Floobits detected OS X 10.12
reloading plugin Floobits.tag_release
reloading plugin Floobits.text_commands
reloading plugin Floobits.window_commands
reloading plugin Random Everything.__init__
reloading plugin Random Everything.random
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter loaded 
reloading plugin WakaTime.WakaTime
plugins loaded
[WakaTime] [INFO] Initializing WakaTime plugin v7.0.20
SublimeLinter: debug mode: off 
SublimeLinter: WARNING: import of pyflakes.api module in pyflakes failed, linter will not work with python 3 code 
Floobits: Called plugin_loaded.
Emmet: No need to update PyV8
Package Control: No updated packages
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 962, in lint_view
    callback(cls.get_view(vid), linters, hit_time)
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 138, in highlight
    vid = view.id()
AttributeError: 'NoneType' object has no attribute 'id'
 
SublimeLinter: -------------------- 
GitGutter: 'git archive' failed with "fatal: pathspec 'src/vendors.js' did not match any files"
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 962, in lint_view
    callback(cls.get_view(vid), linters, hit_time)
  File "/Users/alanhoff/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 138, in highlight
    vid = view.id()
AttributeError: 'NoneType' object has no attribute 'id'
 
SublimeLinter: -------------------- 
GitGutter: 'git archive' failed with "fatal: pathspec 'src/vendors.js' did not match any files"
```

**Comment by alanhoff** [comment]
@deathaxe 's suggestion actually worked :-)

**Comment by Saynah** [comment]
@deathaxe 's suggestion worked for me to!

**Comment by braver** [comment]
Should be better in SL4, check it out!  https://github.com/SublimeLinter/SublimeLinter3#sublimelinter-4-beta
