### ISSUE TITLE
`@python` value needs to be string not float?

### ISSUE THREAD

**Issue by brutus** [SublimeLinter/SublimeLinter3#592]
I use _Sublime Text Build 3126_ and have Python versions 2.7.12, 3.5.2 and 3.6.1 installed. Also _pyflakes_, _pydocstyle_, _pycodestyle_ and _pep8_ are installed for each version of python (with `--user`). BTW: what is the difference between _pycodestyle_ and _pep8_?

Anyway, I want to lint my source using Python 3.6. I quote the [docs](http://sublimelinter.readthedocs.io/en/latest/meta_settings.html#python):

> The @python meta setting is a floating point number that specifies the python version that should be used when running python-based linters.

If I use this in my configuration:

```
{
    "user": {
        "@python": 3.6,
        "debug": true,
        "delay": 0.25,
        …
}
```

I get this error:

```
px_gtk.cc:308 px_init                                             DPI scale: 1
main.cc:469 main                                                  startup, version: 3126 linux x64 channel: stable
main.cc:471 main                                                  executable: /opt/sublime_text/sublime_text
main.cc:472 main                                                  working dir: /home/brutus/Code/Snippets/Python
main.cc:473 main                                                  packages path: /home/brutus/.config/sublime-text-3/Packages
main.cc:474 main                                                  state path: /home/brutus/.config/sublime-text-3/Local
base_app_loader.cc:351 init                                       zip path: /opt/sublime_text/Packages
base_app_loader.cc:352 init                                       zip path: /home/brutus/.config/sublime-text-3/Installed Packages
base_app_loader.cc:150 async_file_read                            ignored_packages: ["Dictionaries", "Markdown", "Theme - Soda SolarizedDark", "Theme - Sodarized", "Vintage"]
app_loader.cc:244 on_app_ready                                    pre session restore time: 0.207499
app_loader.cc:312 on_app_ready                                    startup time: 0.322524
window_impl.cc:193 paint                                          first paint time: 0.324011
window_impl.cc:229 pre_paint                                      first paint time: 0.341379
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-bs4
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Better CoffeeScript.CoffeeScript
reloading plugin ChangeQuotes.change_quotes
reloading plugin EditorConfig.EditorConfig
reloading plugin Emmet.emmet-plugin
reloading plugin GitGutter.plugin
reloading plugin Hipster Ipsum.hipsteripsum
build_controller.cc:497 get_cancel_command                        Unable to find cancel_build command: exec
build_controller.cc:497 get_cancel_command                        Unable to find cancel_build command: exec
reloading plugin Markdown Preview.MarkdownPreview
build_controller.cc:497 get_cancel_command                        Unable to find cancel_build command: exec
build_controller.cc:497 get_cancel_command                        Unable to find cancel_build command: exec
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.decide_title
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.folding
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.mdeutils
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.references
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
reloading plugin MarkdownTOC.MarkdownTOC
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
build_controller.cc:497 get_cancel_command                        Unable to find cancel_build command: exec
build_controller.cc:497 get_cancel_command                        Unable to find cancel_build command: exec
reloading plugin Package Control.Package Control
reloading plugin Select Quoted.select_quotes
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.Stats
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: htmltidy linter loaded 
reloading plugin SublimeLinter-pep8.linter
SublimeLinter: pep8 linter loaded 
reloading plugin SublimeLinter-pydocstyle.linter
SublimeLinter: pydocstyle linter loaded 
reloading plugin SublimeLinter-pyflakes.linter
SublimeLinter: pyflakes linter loaded 
reloading plugin SublimeLinter-pyyaml.linter
SublimeLinter: pyyaml linter loaded 
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin Terminal.Terminal
plugin_api.cc:3136 api_plugin_host_loaded_plugins                 plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /tmp/SublimeLinter3-brutus 
SublimeLinter: find_python(version='3', script=None, module=None) 
SublimeLinter: find_python: requested version = {'major': 3, 'minor': None} 
SublimeLinter: find_posix_python: python3 => /usr/bin/python3 
SublimeLinter: find_python: system python = /usr/bin/python3 
SublimeLinter: find_python: available version = {'major': 3, 'minor': 5} 
SublimeLinter: find_python: <= ('/usr/bin/python3', None, 3, 5) 
SublimeLinter: sys.path for /usr/bin/python3:
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
/home/brutus/.local/lib/python3.5/site-packages
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
 
SublimeLinter: pep8 imported <module 'pep8' from '/home/brutus/.local/lib/python3.5/site-packages/pep8.py'> 
SublimeLinter: pyyaml imported <module 'yaml' from '/home/brutus/.config/sublime-text-3/Packages/pyyaml/st3/yaml/__init__.py'> 
SublimeLinter: pyflakes imported <module 'pyflakes.api' from '/home/brutus/.local/lib/python3.5/site-packages/pyflakes/api.py'> 
SublimeLinter: find_python(version=None, script='pydocstyle', module=None) 
SublimeLinter: find_python: default python = /usr/bin/python 
SublimeLinter: find_python: available version = {'major': 2, 'minor': 7} 
SublimeLinter: find_python: 'pydocstyle' path = /home/brutus/.local/bin/pydocstyle 
SublimeLinter: find_python: <= ('/usr/bin/python', '/home/brutus/.local/bin/pydocstyle', 2, 7) 
SublimeLinter: pydocstyle version query: /usr/bin/python /home/brutus/.local/bin/pydocstyle --version 
SublimeLinter: pydocstyle version: 2.0.0 
SublimeLinter: pydocstyle: (>= 0.3.0) satisfied by 2.0.0 
SublimeLinter: pydocstyle activated: ('/usr/bin/python', '/home/brutus/.local/bin/pydocstyle') 
SublimeLinter: pep8 version: 1.7.0 
SublimeLinter: pep8: (>= 1.4.6) satisfied by 1.7.0 
SublimeLinter: pep8 activated: <builtin> 
SublimeLinter: pyflakes version: 1.5.0 
SublimeLinter: pyflakes: (>= 0.7.3) satisfied by 1.5.0 
SublimeLinter: pyflakes activated: <builtin> 
Emmet: No need to update PyV8
SublimeLinter: pydocstyle: migrate_collation.py ['/usr/bin/python', '/home/brutus/.local/bin/pydocstyle'] 
SublimeLinter: pydocstyle output:
Error in file /tmp/SublimeLinter3-brutus/migrate_collation.py: Cannot parse file. 
SublimeLinter: find_python(version=3.6, script=None, module=<module 'pyflakes.api' from '/home/brutus/.local/lib/python3.5/site-packages/pyflakes/api.py'>) 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 929, in lint_view
    linter.lint(hit_time)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1397, in lint
    output = self.run(cmd, self.code)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/python_linter.py", line 272, in run
    version = util.find_python(version=version, module=self.module)
  File "./python3.3/functools.py", line 251, in wrapper
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/util.py", line 806, in find_python
    elif os.path.isfile(version):
  File "./python3.3/genericpath.py", line 29, in isfile
TypeError: argument should be string, bytes or integer, not float
 
SublimeLinter: -------------------- 
Package Control: Skipping automatic upgrade, last run at 2017-06-30 15:35:38, next run at 2017-06-30 16:35:38 or after
settings_loader.cc:257 on_resource_modified                       reloading settings Packages/User/SublimeLinter.sublime-settings
SublimeLinter: pydocstyle: migrate_collation.py ['/usr/bin/python', '/home/brutus/.local/bin/pydocstyle'] 
SublimeLinter: pydocstyle output:
Error in file /tmp/SublimeLinter3-brutus/migrate_collation.py: Cannot parse file. 
SublimeLinter: find_python(version=3.6, script=None, module=<module 'pyflakes.api' from '/home/brutus/.local/lib/python3.5/site-packages/pyflakes/api.py'>) 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 929, in lint_view
    linter.lint(hit_time)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1397, in lint
    output = self.run(cmd, self.code)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/python_linter.py", line 272, in run
    version = util.find_python(version=version, module=self.module)
  File "./python3.3/functools.py", line 251, in wrapper
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/util.py", line 806, in find_python
    elif os.path.isfile(version):
  File "./python3.3/genericpath.py", line 29, in isfile
TypeError: argument should be string, bytes or integer, not float
 
SublimeLinter: --------------------
```

If I use this in my configuration instead, 

```
{
    "user": {
        "@python": "3.6",
        "debug": true,
        "delay": 0.25,
        …
}
```

it seems to work:

```
px_gtk.cc:308 px_init                                             DPI scale: 1
main.cc:469 main                                                  startup, version: 3126 linux x64 channel: stable
main.cc:471 main                                                  executable: /opt/sublime_text/sublime_text
main.cc:472 main                                                  working dir: /home/brutus/Code/Snippets/Python
main.cc:473 main                                                  packages path: /home/brutus/.config/sublime-text-3/Packages
main.cc:474 main                                                  state path: /home/brutus/.config/sublime-text-3/Local
base_app_loader.cc:351 init                                       zip path: /opt/sublime_text/Packages
base_app_loader.cc:352 init                                       zip path: /home/brutus/.config/sublime-text-3/Installed Packages
base_app_loader.cc:150 async_file_read                            ignored_packages: ["Dictionaries", "Markdown", "Theme - Soda SolarizedDark", "Theme - Sodarized", "Vintage"]
app_loader.cc:244 on_app_ready                                    pre session restore time: 0.227304
app_loader.cc:312 on_app_ready                                    startup time: 0.343568
window_impl.cc:193 paint                                          first paint time: 0.345107
window_impl.cc:229 pre_paint                                      first paint time: 0.374661
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-bs4
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Better CoffeeScript.CoffeeScript
reloading plugin ChangeQuotes.change_quotes
reloading plugin EditorConfig.EditorConfig
reloading plugin Emmet.emmet-plugin
reloading plugin GitGutter.plugin
reloading plugin Hipster Ipsum.hipsteripsum
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.decide_title
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.folding
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.mdeutils
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.references
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
reloading plugin MarkdownTOC.MarkdownTOC
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Select Quoted.select_quotes
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.Stats
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: htmltidy linter loaded 
reloading plugin SublimeLinter-pep8.linter
SublimeLinter: pep8 linter loaded 
reloading plugin SublimeLinter-pydocstyle.linter
SublimeLinter: pydocstyle linter loaded 
reloading plugin SublimeLinter-pyflakes.linter
SublimeLinter: pyflakes linter loaded 
reloading plugin SublimeLinter-pyyaml.linter
SublimeLinter: pyyaml linter loaded 
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin Terminal.Terminal
plugin_api.cc:3136 api_plugin_host_loaded_plugins                 plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /tmp/SublimeLinter3-brutus 
SublimeLinter: find_python(version='3', script=None, module=None) 
SublimeLinter: find_python: requested version = {'major': 3, 'minor': None} 
SublimeLinter: find_posix_python: python3 => /usr/bin/python3 
SublimeLinter: find_python: system python = /usr/bin/python3 
SublimeLinter: find_python: available version = {'major': 3, 'minor': 5} 
SublimeLinter: find_python: <= ('/usr/bin/python3', None, 3, 5) 
SublimeLinter: sys.path for /usr/bin/python3:
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
/home/brutus/.local/lib/python3.5/site-packages
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
 
SublimeLinter: pep8 imported <module 'pep8' from '/home/brutus/.local/lib/python3.5/site-packages/pep8.py'> 
SublimeLinter: pyyaml imported <module 'yaml' from '/home/brutus/.config/sublime-text-3/Packages/pyyaml/st3/yaml/__init__.py'> 
SublimeLinter: pyflakes imported <module 'pyflakes.api' from '/home/brutus/.local/lib/python3.5/site-packages/pyflakes/api.py'> 
SublimeLinter: pep8 version: 1.7.0 
SublimeLinter: pep8: (>= 1.4.6) satisfied by 1.7.0 
SublimeLinter: pep8 activated: <builtin> 
SublimeLinter: find_python(version=None, script='pydocstyle', module=None) 
SublimeLinter: find_python: default python = /usr/bin/python 
SublimeLinter: find_python: available version = {'major': 2, 'minor': 7} 
SublimeLinter: find_python: 'pydocstyle' path = /home/brutus/.local/bin/pydocstyle 
SublimeLinter: find_python: <= ('/usr/bin/python', '/home/brutus/.local/bin/pydocstyle', 2, 7) 
SublimeLinter: pydocstyle version query: /usr/bin/python /home/brutus/.local/bin/pydocstyle --version 
SublimeLinter: pydocstyle version: 2.0.0 
SublimeLinter: pydocstyle: (>= 0.3.0) satisfied by 2.0.0 
SublimeLinter: pydocstyle activated: ('/usr/bin/python', '/home/brutus/.local/bin/pydocstyle') 
SublimeLinter: pyflakes version: 1.5.0 
SublimeLinter: pyflakes: (>= 0.7.3) satisfied by 1.5.0 
SublimeLinter: pyflakes activated: <builtin> 
Emmet: No need to update PyV8
SublimeLinter: pydocstyle: migrate_collation.py ['/usr/bin/python', '/home/brutus/.local/bin/pydocstyle'] 
SublimeLinter: pydocstyle output:
Error in file /tmp/SublimeLinter3-brutus/migrate_collation.py: Cannot parse file. 
SublimeLinter: find_python(version='3.6', script=None, module=<module 'pep8' from '/home/brutus/.local/lib/python3.5/site-packages/pep8.py'>) 
SublimeLinter: find_python: requested version = {'major': 3, 'minor': 6} 
SublimeLinter: find_python: available version = {'major': 3, 'minor': 3} 
SublimeLinter: find_posix_python: python3.6 => /usr/bin/python3.6 
SublimeLinter: find_python: system python = /usr/bin/python3.6 
SublimeLinter: find_python: available version = {'major': 3, 'minor': 6} 
SublimeLinter: find_python: <= ('/usr/bin/python3.6', None, 3, 6) 
SublimeLinter: find_python(version='3.6', script='pep8', module=<module 'pep8' from '/home/brutus/.local/lib/python3.5/site-packages/pep8.py'>) 
SublimeLinter: find_python: requested version = {'major': 3, 'minor': 6} 
SublimeLinter: find_python: available version = {'major': 3, 'minor': 3} 
SublimeLinter: find_python: system python = /usr/bin/python3.6 
SublimeLinter: find_python: available version = {'major': 3, 'minor': 6} 
SublimeLinter: find_python: 'pep8' path = /home/brutus/.local/bin/pep8 
SublimeLinter: find_python: <= ('/usr/bin/python3.6', '/home/brutus/.local/bin/pep8', 3, 6) 
SublimeLinter: pep8: migrate_collation.py ['/usr/bin/python3.6', '/home/brutus/.local/bin/pep8', '-'] 
SublimeLinter: pep8 output:
stdin:12:1: W191 indentation contains tabs
stdin:14:1: W191 indentation contains tabs
stdin:15:1: W191 indentation contains tabs
stdin:16:1: W191 indentation contains tabs
stdin:18:1: W191 indentation contains tabs
stdin:20:1: W191 indentation contains tabs
stdin:22:1: W191 indentation contains tabs
stdin:24:1: W191 indentation contains tabs
stdin:26:1: W191 indentation contains tabs
stdin:27:1: W191 indentation contains tabs
stdin:28:1: W191 indentation contains tabs
stdin:29:1: W191 indentation contains tabs
stdin:30:1: W191 indentation contains tabs
stdin:31:1: W191 indentation contains tabs
stdin:32:1: W191 indentation contains tabs
stdin:33:1: W191 indentation contains tabs
stdin:34:1: W191 indentation contains tabs
stdin:35:1: W191 indentation contains tabs
stdin:36:1: W191 indentation contains tabs
stdin:37:1: W191 indentation contains tabs
stdin:38:1: W191 indentation contains tabs
stdin:39:1: W191 indentation contains tabs
stdin:40:1: W191 indentation contains tabs
stdin:41:1: W191 indentation contains tabs
stdin:42:1: W191 indentation contains tabs
stdin:44:1: W191 indentation contains tabs
stdin:49:1: W191 indentation contains tabs
stdin:51:1: W191 indentation contains tabs
stdin:52:1: W191 indentation contains tabs
stdin:54:1: W191 indentation contains tabs
stdin:55:1: W191 indentation contains tabs
stdin:56:1: W191 indentation contains tabs
stdin:57:1: W191 indentation contains tabs
stdin:58:1: W191 indentation contains tabs
stdin:59:1: W191 indentation contains tabs
stdin:60:1: W191 indentation contains tabs 
SublimeLinter: find_python(version='3.6', script=None, module=<module 'pyflakes.api' from '/home/brutus/.local/lib/python3.5/site-packages/pyflakes/api.py'>) 
SublimeLinter: find_python: requested version = {'major': 3, 'minor': 6} 
SublimeLinter: find_python: available version = {'major': 3, 'minor': 3} 
SublimeLinter: find_python: system python = /usr/bin/python3.6 
SublimeLinter: find_python: available version = {'major': 3, 'minor': 6} 
SublimeLinter: find_python: <= ('/usr/bin/python3.6', None, 3, 6) 
SublimeLinter: find_python(version='3.6', script='pyflakes', module=<module 'pyflakes.api' from '/home/brutus/.local/lib/python3.5/site-packages/pyflakes/api.py'>) 
SublimeLinter: find_python: requested version = {'major': 3, 'minor': 6} 
SublimeLinter: find_python: available version = {'major': 3, 'minor': 3} 
SublimeLinter: find_python: system python = /usr/bin/python3.6 
SublimeLinter: find_python: available version = {'major': 3, 'minor': 6} 
SublimeLinter: find_python: 'pyflakes' path = /home/brutus/.local/bin/pyflakes 
SublimeLinter: find_python: <= ('/usr/bin/python3.6', '/home/brutus/.local/bin/pyflakes', 3, 6) 
SublimeLinter: pyflakes: migrate_collation.py ['/usr/bin/python3.6', '/home/brutus/.local/bin/pyflakes'] 
Package Control: Skipping automatic upgrade, last run at 2017-06-30 15:35:38, next run at 2017-06-30 16:35:38 or after
```

So, is this working as intended?

**Comment by braver** [comment]
@brutus I cannot reproduce this, it takes a float just fine. What is the exact setup and project where you're having this problem?

**Comment by brutus** [comment]
Sorry for not responding sooner. I can still reproduce this. When running _Sublime Text Build 3143_ with _Sublime Linter 3.10.4_.

```
"SublimeLinter":
{
    "@python": "2.7"
}
```

When I open a Python file while having `"2.7"` or `"3.6"` set (with quotation marks), linting works:

```
SublimeLinter: pyflakes version: 1.5.0
SublimeLinter: pyflakes: (>= 0.7.3) satisfied by 1.5.0
SublimeLinter: pyflakes activated: <builtin>
SublimeLinter: find_python(version='2.7', script=None, module=<module 'pyflakes.api' from '/home/brutus/.local/lib/python3.5/site-packages/pyflakes/api.py'>)
SublimeLinter: find_python: requested version = {'major': 2, 'minor': 7}
SublimeLinter: find_python: available version = {'major': 3, 'minor': 3}
SublimeLinter: find_posix_python: python2.7 => /usr/bin/python2.7
SublimeLinter: find_python: system python = /usr/bin/python2.7
SublimeLinter: find_python: available version = {'major': 2, 'minor': 7}
SublimeLinter: find_python: <= ('/usr/bin/python2.7', None, 2, 7)
SublimeLinter: find_python(version='2.7', script='pyflakes', module=<module 'pyflakes.api' from '/home/brutus/.local/lib/python3.5/site-packages/pyflakes/api.py'>)
SublimeLinter: find_python: requested version = {'major': 2, 'minor': 7}
SublimeLinter: find_python: available version = {'major': 3, 'minor': 3}
SublimeLinter: find_python: system python = /usr/bin/python2.7
SublimeLinter: find_python: available version = {'major': 2, 'minor': 7}
SublimeLinter: find_python: 'pyflakes' path = /home/brutus/.local/bin/pyflakes
SublimeLinter: find_python: <= ('/usr/bin/python2.7', '/home/brutus/.local/bin/pyflakes', 2, 7)
SublimeLinter: pyflakes: paternoster.py ['/usr/bin/python2.7', '/home/brutus/.local/bin/pyflakes']
SublimeLinter: pyflakes output:
<stdin>:14: 'paternoster.types' imported but unused
SublimeLinter: pyflakes: setup.py ['/usr/bin/python2.7', '/home/brutus/.local/bin/pyflakes']
```

When set `2.7` or `3.6` (without quotation marks), linting breaks:

```
SublimeLinter: json output:
Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):20:23
SublimeLinter: find_python(version=2.7, script=None, module=<module 'pyflakes.api' from '/home/brutus/.local/lib/python3.5/site-packages/pyflakes/api.py'>)
SublimeLinter: error in SublimeLinter daemon:
SublimeLinter: --------------------
SublimeLinter: Traceback (most recent call last):
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 121, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 968, in lint_view
    linter.lint(hit_time)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1436, in lint
    output = self.run(cmd, self.code)
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/python_linter.py", line 272, in run
    version = util.find_python(version=version, module=self.module)
  File "./python3.3/functools.py", line 251, in wrapper
  File "/home/brutus/.config/sublime-text-3/Packages/SublimeLinter/lint/util.py", line 806, in find_python
    elif os.path.isfile(version):
  File "./python3.3/genericpath.py", line 29, in isfile
TypeError: argument should be string, bytes or integer, not float
```
