### ISSUE TITLE
error when installing any new package or disabling the plugin

### ISSUE THREAD

**Issue by ctf0** [SublimeLinter/SublimeLinter3#596]
![screen shot 2017-07-08 at 11 07 02 pm](https://user-images.githubusercontent.com/7388088/27989133-3fdcd1c4-6432-11e7-928e-34d3579f30ed.jpg)

and sometimes its
```log
Traceback (most recent call last):
  File "/Users/novo/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 247, in generate_color_scheme_async
    scheme_text = sublime.load_resource(scheme)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
Package Control: Settings change detected, clearing cache
error: Error loading colour scheme Packages/Color Scheme - Default/Monokai.tmTheme: Unable to open Packages/Color Scheme - Default/Monokai.tmTheme
error: Error loading colour scheme Packages/Color Scheme - Default/Monokai.tmTheme: Unable to open Packages/Color Scheme - Default/Monokai.tmTheme
error: Error loading colour scheme Packages/Color Scheme - Default/Monokai.tmTheme: Unable to open Packages/Color Scheme - Default/Monokai.tmTheme
```

**Comment by braver** [comment]
Looks like you're missing some color schemes. What happens if you install the latest release of Sublime Text 3.0 and reinstall the SublimeLinter package?

**Comment by ctf0** [comment]
actually for some time now no errors, so will close it for now until something comes up later
