### ISSUE TITLE
UnboundLocalError: local variable 'executable' referenced before assignment“

### ISSUE THREAD

**Issue by dingo-d** [SublimeLinter/SublimeLinter3#601]
My linters worked, but suddenly stopped. I have eslint, phpcs and scss linters installed, but none of them seem to be working. Console throws this error

~~~py
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 279, in on_activated
    self.check_syntax(view)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 206, in check_syntax
    Linter.assign(view, reset=True)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 734, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./python3.3/functools.py", line 251, in wrapper
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1602, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
UnboundLocalError: local variable 'executable' referenced before assignment“
~~~

My settings are

~~~json
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "eslint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "phpcs": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "standard": "WordPress"
            },
            "scss": {
                "@disable": true,
                "args": [],
                "exclude-linter": "",
                "excludes": [],
                "include-linter": ""
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [
                "/Users/user/wpcs/vendor/bin"
            ],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "tooltip_fontsize": "1rem",
        "tooltip_theme": "Packages/SublimeLinter/tooltip-themes/Default/Default.tooltip-theme",
        "tooltip_theme_excludes": [],
        "tooltips": false,
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
~~~

I am on MacOS Sierra 10.12.6, SublimeText 3 Build 3126.

**Comment by braver** [comment]
Did your linters ever start working again after this?

**Comment by dingo-d** [comment]
Yes, I updated the sublime, and checked one project and it seems to be working. I cannot remember on what project this didn't work on :S
