### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'views'

### ISSUE THREAD

**Issue by evandrocoan** [SublimeLinter/SublimeLinter3#607]
This showed up when I opened a project:
```
Traceback (most recent call last):
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\__init__.py", line 174, in do_linting
    and USER_PATH in self.view.file_name()
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\__init__.py", line 174, in do_linting
    and USER_PATH in self.view.file_name()
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "D:\SublimeText\Data\Packages\SublimeLinter\sublimelinter.py", line 394, in on_selection_modified_async
    view = self.get_focused_view_id(view)
  File "D:\SublimeText\Data\Packages\SublimeLinter\sublimelinter.py", line 384, in get_focused_view_id
    for view in view.window().views():
AttributeError: 'NoneType' object has no attribute 'views'
Finished normally
```

___ 

Related:

1. https://github.com/SublimeText/PackageDev/issues/129 TypeError: argument of type 'NoneType' is not iterable
1. https://github.com/SublimeLinter/SublimeLinter3/issues/570 SublimeLinter deamon crashes on fast view changes

### Environment

* Operating system and version:
  * Windows 10 build 15063 x64
  * Mac OS ...
  * Linux ...
* Monitor:
  * Resolution 1920x1080
  * `dpi_scale` used in ST 1.0
* Sublime Text:
  * Build 3142
  * 32 bit

1. https://github.com/SublimeLinter/SublimeLinter3/blob/a5f6c28ac7d88bfe28d524f6c2a6c2ed6b563cbc/sublimelinter.py#L351-L356
1. https://github.com/evandrocoan/SublimeLinter3/blob/23581518a17050ca9692cce6ab733f4e081acdcf/sublimelinter.py#L384-L390

**Comment by toxinu** [comment]
Same error for me.

**Comment by braver** [comment]
closing in favour of #570
