### ISSUE TITLE
Not well formed xml related error

### ISSUE THREAD

**Issue by toxinu** [SublimeLinter/SublimeLinter3#610]
Hi there,

I'm still having this error every time I launch SublimeText.

```python
Traceback (most recent call last):
  File "~/.config/sublime-text-3/Packages/SublimeLinter/lint/util.py", line 264, in generate_color_scheme_async
    plist = ElementTree.XML(scheme_text)
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 8, column 2
Traceback (most recent call last):
  File "~/.config/sublime-text-3/Packages/SublimeLinter/lint/util.py", line 264, in generate_color_scheme_async
    plist = ElementTree.XML(scheme_text)
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 8, column 2
```
Which information can I provide to help?

**Comment by toxinu** [comment]
It was related to my not well formed color scheme xml. Sorry about that!
