### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'active_view'

### ISSUE THREAD

**Issue by evandrocoan** [SublimeLinter/SublimeLinter3#620]
I just saw this on my console, after I opened a new window, but I am not sure on how to reproduce:
```
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "D:\SublimeText\Data\Packages\SublimeLinter\sublimelinter.py", line 394, in on_selection_modified_async
    view = self.get_focused_view_id(view)
  File "D:\SublimeText\Data\Packages\SublimeLinter\sublimelinter.py", line 382, in get_focused_view_id
    active_view = view.window().active_view()
AttributeError: 'NoneType' object has no attribute 'active_view'
Could not determine project file as view does not seem to have an associated window.
```

Lines:
```python
File: SublimeLinter/sublimelinter.py
373:     def get_focused_view_id(self, view):
374:         """
375:         Return the focused view which shares view's buffer.
376: 
377:         When updating the status, we want to make sure we get
378:         the selection of the focused view, since multiple views
379:         into the same buffer may be open.
380: 
381:         """
382:         active_view = view.window().active_view()
383: 
384:         for view in view.window().views():
385:             if view == active_view:
386:                 return view
````

____

Related:

1. https://github.com/SublimeLinter/SublimeLinter3/issues/186 AttributeError since build 3069

**Comment by babygau** [comment]
I had the same error but in different location

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 465, in on_pre_save_async
    callback.on_pre_save_async(v)
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 470, in on_pre_save_async
    if view.window().active_view() == view and self.is_settings_file(view):
AttributeError: 'NoneType' object has no attribute 'active_view'
```

**Comment by braver** [comment]
This may just be an asynchronisity issue that pops ups in weird situations. I'm not sure if we should guard against that, but it should be easy enough, e.g.: https://github.com/SublimeLinter/SublimeLinter3/pull/611/files#diff-e4e8a30eb88a08e1933dc3a042bde8b2R350

@groteworld I don't get this error and you weren't able to reproduce in #186 either. Any ideas/opinions?

**Comment by braver** [comment]
We got a guard in place for this now
