### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by PvtFudgepants** [SublimeLinter/SublimeLinter3#638]
Tried to look around for similar errors, but I can't seem to find any. I got this working fine on my pc at work, but my home pc seems to be giving me this error.

Any help would be appreciated

```
SublimeLinter: jshint version query: C:\Users\Chris\AppData\Roaming\npm\jshint.cmd --version 
SublimeLinter: jshint version: 2.9.5 
SublimeLinter: jshint: (>= 2.5.0) satisfied by 2.9.5 
SublimeLinter: jshint activated: C:\Users\Chris\AppData\Roaming\npm\jshint.cmd 
Traceback: error.

Output:


Error:
Invalid Parameter - TrueColorMatte


Highlighting colors with gutter icons is not supported with current ImageMagick setup. Try configuring the "icon_factory setting"
Emmet: No need to update PyV8
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Users\Chris\Desktop\Programs\Sublime Text\Data\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Chris\Desktop\Programs\Sublime Text\Data\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "C:\Users\Chris\Desktop\Programs\Sublime Text\Data\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "C:\Users\Chris\Desktop\Programs\Sublime Text\Data\Packages\SublimeLinter\sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\Chris\Desktop\Programs\Sublime Text\Data\Packages\SublimeLinter\lint\linter.py", line 923, in lint_view
    view_settings = linter.get_view_settings(inline=False)
  File "./python3.3/functools.py", line 251, in wrapper
  File "C:\Users\Chris\Desktop\Programs\Sublime Text\Data\Packages\SublimeLinter\lint\linter.py", line 449, in get_view_settings
    settings = self.get_merged_settings()
  File "C:\Users\Chris\Desktop\Programs\Sublime Text\Data\Packages\SublimeLinter\lint\linter.py", line 496, in get_merged_settings
    self.replace_settings_tokens(settings)
  File "C:\Users\Chris\Desktop\Programs\Sublime Text\Data\Packages\SublimeLinter\lint\linter.py", line 590, in replace_settings_tokens
    folders = window.project_data()['folders']
TypeError: 'NoneType' object is not subscriptable
 
SublimeLinter: -------------------- 
```

**Comment by groteworld** [comment]
Fix was entered in v3.10.1

Restarting SublimeText should download this.
