### ISSUE TITLE
"OSError: resource not found" after install

### ISSUE THREAD

**Issue by Svish** [SublimeLinter/SublimeLinter3#664]
Had some issues with ST3, so decided to reinstall to get a fresh start. Uninstalled ST3, and deleted ST3 folders in %appdata%.

When I now install the SublimeLinter package (via Install Package command), I get an `OSError: resource not found` in the console:

**After opening ST3 (in case it's related to other packages or something)**
```
DPI scale: 1
startup, version: 3154 windows x64 channel: dev
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/torleif/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/torleif/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/torleif/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.100091
startup time: 0.151091
first paint time: 0.157091
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Codec.codec_base64
reloading plugin Codec.codec_hex
reloading plugin Codec.codec_idn
reloading plugin Codec.codec_json
reloading plugin Codec.codec_quopri
reloading plugin Codec.codec_xml
reloading plugin Codec.sublime_codec
reloading plugin HexViewer.hex_checksum
Hex Viewer: md2 hash is not available!
reloading plugin HexViewer.hex_common
reloading plugin HexViewer.hex_editor
reloading plugin HexViewer.hex_finder
reloading plugin HexViewer.hex_highlighter
reloading plugin HexViewer.hex_inspector
reloading plugin HexViewer.hex_notify
reloading plugin HexViewer.hex_viewer
reloading plugin HexViewer.hex_writer
reloading plugin HexViewer.sum_hashes
reloading plugin HexViewer.support
reloading plugin HexViewer.tiger
reloading plugin HexViewer.whirlpool
reloading plugin LESS.less_completions
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Open URL.example
reloading plugin Open URL.open_url
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PhpDoc.CodeDoc
reloading plugin Text Pastry.text_pastry
reloading plugin Text Pastry.text_pastry_addons
reloading plugin Text Pastry.text_pastry_clipboard
reloading plugin Text Pastry.text_pastry_selection
reloading plugin ColorPicker.sublimecp
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2017-11-12 18:40:01, next run at 2017-11-12 19:40:01 or after
```

**After Install Package SL**
``` 
ignored packages updated to: ["SublimeLinter", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
Traceback (most recent call last):
  File "C:\Users\torleif\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 247, in generate_color_scheme_async
    scheme_text = sublime.load_resource(scheme)
  File "C:\Program Files\Sublime Text 3\sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "C:\Users\torleif\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 247, in generate_color_scheme_async
    scheme_text = sublime.load_resource(scheme)
  File "C:\Program Files\Sublime Text 3\sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
reloading settings Packages/User/Preferences.sublime-settings
```

Don't know if I had this error before the fresh start (was an unrelated issue that made me do that) as I haven't really watched the console before... is it "supposed to happen"? Is it not really an issue? ...what is it not finding? I get the same error everytime I restart ST3 and also whenever I install another SL linter
 package. 😟

**Comment by cagross** [comment]
I think I have a similar issue. I have attached my debug log to the bottom of this message.  I have some additional information:

--If I open Tools-->SublimeLinter-->"Toggle linter..." I see that jshint is `enbabled`.
--If I try to run 'jshint' from the SublimeText command line, it outputs an error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'jshint' is not defined
```

I thought this might be an issue with my PATH (as described [here](http://sublimelinter.readthedocs.io/en/latest/troubleshooting.html#debugging-path-problems)). But I'm not encountering any of the errors indicated on that page.

I am open to try any troubleshooting steps.  I am running SublimeText v3.0 build 3143 on Win 10, x64.

Thanks.

```
DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/snarl/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/snarl/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/snarl/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
"Packages/Color Scheme - Default/Sunburst.tmTheme" is no longer maintained and is now part of "Color Scheme - Legacy"
pre session restore time: 0.0844815
startup time: 0.119482
first paint time: 0.120482
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin SublimeLinter-jsxhint.linter
SublimeLinter: jsxhint linter loaded 
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin User.toggle_comment_cag8f
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: c:\users\snarl\appdata\local\temp\SublimeLinter3-snarl 
Traceback (most recent call last):
  File "C:\Users\snarl\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 247, in generate_color_scheme_async
    scheme_text = sublime.load_resource(scheme)
  File "C:\Program Files\Sublime Text 3\sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
Package Control: Skipping automatic upgrade, last run at 2017-11-15 23:43:50, next run at 2017-11-16 00:43:50 or after
```

**Comment by braver** [comment]
I think this might be caused by SL not finding your color scheme for some reason. Does the error go away if you select a different color scheme and restart Sublime?

**Comment by jontewks** [comment]
@braver I'm getting this as well. The issue goes away when I select the Monokai Phoenix color scheme but comes back whenever I choose the built in Monokai.

**Comment by jontewks** [comment]
@braver ah, issue is resolved for me by using the stable release version of sublime and not the dev channel release 😳 . Thanks!

**Comment by braver** [comment]
Oh, that makes sense, we’re not compatible with the dev build yet. It’s coming though: #666
