### ISSUE TITLE
SL keeps crashing while linting python code

### ISSUE THREAD

**Issue by deathaxe** [SublimeLinter/SublimeLinter3#675]
### specs

- Windows 10 x64 1703
- ST 3156 x64 portable
- SL beta 4 commit 1176722

enabled SL plugins
- sublimelinter-pep8
- sublimelinter-pydocstyle
- sublimelinter-pylint

The issue seems to be triggered while editing source code.

### error log

```
Unknown option 'max-line-length' ignored
Traceback (most recent call last):
  File "C:\Apps\Sublime\sublime_plugin.py", line 521, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\sublime_linter.py", line 125, in on_selection_modified_async
    self.display_errors(view)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\sublime_linter.py", line 391, in display_errors
    view = util.get_focused_view(view)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\util.py", line 109, in get_focused_view
    active_view = get_active_view(view)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\util.py", line 96, in get_active_view
    return view.window().active_view()
AttributeError: 'NoneType' object has no attribute 'active_view'
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\sublime_linter.py", line 266, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\linter.py", line 1000, in lint_view
    callback(cls.get_view(vid), linters, hit_time)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\sublime_linter.py", line 319, in highlight
    highlights.draw(other_view)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\highlight.py", line 133, in draw
    all.draw(view)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\highlight.py", line 456, in draw
    icon = self.style_store.get_val("icon", style, err_type)
  File "C:\Apps\Sublime\Data\Packages\SublimeLinter\lint\style.py", line 37, in wrapper
    if res != os.path.basename(res):
  File "./python3.3/ntpath.py", line 249, in basename
  File "./python3.3/ntpath.py", line 220, in split
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()

```

### SublimeLinter.sublime-settings

```
{
    "debug": false,
    "delay": 0.3,
    "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
    "lint_mode": "background",
    "linters": {
        "pep8": {
            "@disable": false,
            "args": [],
            "excludes": [],
            "ignore": "",
            "max-line-length": null,
            "select": ""
        },
        "pydocstyle": {
            "@disable": false,
            "add-ignore": "",
            "add-select": "",
            "args": [],
            "config": "",
            "convention": "",
            "excludes": [],
            "ignore": "",
            "ignore-decorators": "",
            "select": ""
        },
        "pyflakes": {
            "@disable": false,
            "args": [],
            "excludes": []
        },
        "pylint": {
            "@disable": false,
            "args": [],
            "disable": "",
            "enable": "",
            "excludes": [],
            "paths": [],
            "rcfile": "",
            "show-codes": false
        }
    },
    "no_column_highlights_line": false,
    "paths": {
        "linux": [],
        "osx": [],
        "windows": []
    },
    "python_paths": {
        "linux": [],
        "osx": [],
        "windows": []
    },
    "rc_search_limit": 3,
    "shell_timeout": 10,
    "show_errors_on_save": false,
    "show_hover_line_report": true,
    "show_marks_in_minimap": true,
    "styles": [
        {
            "mark_style": "outline",
            "priority": 1,
            "scope": "region.yellowish",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "outline",
            "priority": 1,
            "scope": "region.redish",
            "types": [
                "error"
            ]
        }
    ],
    "syntax_map": {
        "html (django)": "html",
        "html (rails)": "html",
        "html 5": "html",
        "javascript (babel)": "javascript",
        "magicpython": "python",
        "php": "html",
        "python django": "python",
        "pythonimproved": "python"
    },
    "wrap_find": true
}
```

**Comment by braver** [comment]
@pykong seems isolated to your fork

**Comment by gerardroche** [comment]
I see some people who tracking the next branch are stuck on old styles scopes i.e. `"scope": "region.yellowish",` oppose to `region.yellowish markup.warning.sublime_linter`.

**Comment by gerardroche** [comment]
In fact, that's where the error is. The styles definition is cause the exception.

Update the "styles" setting to this:


```

    "styles":
    [
        {
            "icon": "warning",
            "mark_style": "fill",
            "priority": 1,
            "scope": "region.yellowish markup.warning.sublime_linter",
            "types":
            [
                "warning"
            ]
        },
        {
            "icon": "error",
            "mark_style": "fill",
            "priority": 1,
            "scope": "region.redish markup.error.sublime_linter",
            "types":
            [
                "error"
            ]
        }
    ],
```
And set `"no_column_highlights_line": true,` (required for the "fill" style, not sure why). Alternatively, set the mark_style to "outline" or whatever you prefer.

**Comment by braver** [comment]
I'm not reproducing this right now, the next branch seems pretty stable and a lot has been done since this was opened. We'll do a real beta release soon, if it's still broken then, please re-open or create a new issue.

**Comment by gerardroche** [comment]
@braver define a custom styles setting like this:

```
    "styles":
    [
        {
            "icon": "warning",
            "mark_style": "fill",
            "priority": 1,
            "scope": "region.yellowish markup.warning.sublime_linter",
            "types":
            [
                "warning"
            ]
        }
    ]
```

or 

```
    "styles":
    [
        {
            "icon": "warning",
            "mark_style": "fill"
        }
    ]
```

**Comment by pykong** [comment]
I will right now look into it.

**Comment by gerardroche** [comment]
I should note too that there could be easier way to set the mark style. The vast majority of users will never need to define a full styles setting. Mostly they only want to change the style i.e. "fill", "outline", etc. It should be very rare that user needs to change the styles (other than the mark style).

**Comment by pykong** [comment]
@gerardroche You are making strong assumptions about what users want. Let's see what the actual feedback from the beta will be like.
If you got constructive feedback to share please do that.

**Comment by gerardroche** [comment]
I assumed it was constructive.

**Comment by pykong** [comment]
Exchange 'constructive' with 'tangible' then.

**Comment by braver** [comment]
Assuming we don’t change the styles object layout on our end a lot it’s simple enough already. It’s a trade off against implementation efficiency, which is why you start with an mvp and then validate the design before brainstorming about optimization’s.

 It should fail kinda gracefully though.

**Comment by pykong** [comment]
I can not produce any crashes with the information given.
@gerardroche @deathaxe Please check again once the beta release is out.

**Comment by braver** [comment]
@deathaxe @gerardroche thanks so much for your time already. We've been testing and tuning and your input has been invaluable. A 4.0.0-rc.7 has been tagged right now (might take some time to trickle through). It seems to work correctly with those same linters. If you would like to give it a go again that would be awesome. If anything is up, let me know in a new issue. Please note that you need to restart ST after the upgrade.

**Comment by deathaxe** [comment]
As @gerardroche correctly stated the exception is triggered by malformed style settings. Removing those from the SublimeLinter.sublime-settings solved the issue.

```
    "styles": [
        {
            "mark_style": "outline",
            "priority": 1,
            "scope": "region.yellowish",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "outline",
            "priority": 1,
            "scope": "region.redish",
            "types": [
                "error"
            ]
        }
    ],
```

They cause the https://github.com/SublimeLinter/SublimeLinter3/blob/32844c59b401bf0b2af7cf07f5a28a48ab72764f/lint/style.py#L54 to return `None` which is not handled by https://github.com/SublimeLinter/SublimeLinter3/blob/32844c59b401bf0b2af7cf07f5a28a48ab72764f/lint/style.py#L31 causing the exception.

Maybe this situation is worth handling?

**Comment by braver** [comment]
@deathaxe thanks for catching this, I'll try to repro and fix.

**Comment by braver** [comment]
Ok, nice. We already catch a number of similar situations. I feel like it could be cleaner architecturally, but bafa513fadd8e5aa329a489ab248f6cf1972d362 fixes it. rc.8 has been tagged. Thanks all!
