### ISSUE TITLE
[pre] Update to 4.0.0-rc.1 causes failed plugin loads

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter3#687]
When updating to the new version, the following tracebacks appeared on the console:

```
reloading plugin SublimeLinter.commands
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'SublimeLinter.commands'
reloading plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'SublimeLinter.sublime_linter'
```

As a result, the plugin seemingly wasn't initialized correctly and also failed to backup the User settings file.

I'm not sure what this means exactly, but you *might* have to do something similar to what I do with PackageDev here: https://github.com/SublimeText/PackageDev/blob/master/main.py. Not sure if that actually works, though, since I never tested the update process.

Note that the plugin loads after an ST restart.

I'm on Arch and 3156.

**Comment by braver** [comment]
Not sure what all this means or what can be done about it. I made sure you don't get swamped in popups, and the upgrade message now tells you to restart (which isn't unreasonable for an upgrade). I don't know if it's worth the effort to try and make the upgrade cleaner than that given how the runtime is really just one big ball of python.
