### ISSUE TITLE
[pre] api changes crash some linter plugins

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter3#688]
After restarting ST to properly have the update apply, I received multiple instances of the following two tracebacks (more of the former):

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 47, in loop
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 55, in loop
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 101, in lint
  File "sublime_linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 264, in lint
  File "lint.linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 1006, in lint_view
  File "sublime_linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 323, in highlight
  File "panel.panel in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 122, in fill_panel
  File "panel.panel in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 69, in create_path_dict
  File "panel.panel in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 69, in <dictcomp>
  File "./python3.3/posixpath.py", line 458, in relpath
ValueError: no path specified
```

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 47, in loop
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 55, in loop
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 101, in lint
  File "sublime_linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 264, in lint
  File "lint.linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 995, in lint_view
  File "lint.linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 1319, in lint
  File "linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter-annotations.sublime-package", line 99, in run
TypeError: range() got an unexpected keyword argument 'error_type'
```

**Comment by FichteFoll** [comment]
Spotted another one:

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 47, in loop
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 55, in loop
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 101, in lint
  File "sublime_linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 264, in lint
  File "lint.linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 1006, in lint_view
  File "sublime_linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 323, in highlight
  File "panel.panel in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 122, in fill_panel
  File "panel.panel in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 62, in create_path_dict
  File "./python3.3/posixpath.py", line 106, in split
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by FichteFoll** [comment]
Another one

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 47, in loop
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 55, in loop
  File "lint.queue in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 101, in lint
  File "sublime_linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 264, in lint
  File "lint.linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 973, in lint_view
  File "lint.linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 1395, in lint
  File "lint.linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 1629, in error
  File "lint.linter in /home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 1614, in escape_html
TypeError: expected string or buffer
```

**Comment by FichteFoll** [comment]
By the way, it would probably be a good idea to get rid of the `During handling of the above exception, another exception occurred:` part by moving whatever code is ending up calling deeper into the stack out of the exception handler of `queue.Empty`.

**Comment by braver** [comment]
@pykong `error_type` has been renamed `err_type`, which is one of the things that seems to break the annotations linter plugin.

**Comment by FichteFoll** [comment]
Doesn't strike me as a good idea to change the idiomatic "error" to just "err" when we're not hunting down characters and also break compatibility at the same time tbh.

**Comment by braver** [comment]
Alrighty, seems like I fixed most of these.

From the top:

1. We show file paths in the output panel, but a view might exist on disk (e.g. an unsaved "untitled" view)
2. The refactor didn't help but that was half the problem. For some reason it fails to set a style for the annotations linter and highlight them, but we'll figure that out later.
3. Probably the same as 1.
4. I replaced some probably pretty ancient 50 something lines with a `html.encode`, should fix that.

@FichteFoll thanks so much for your time already. I just tagged a 4.0.0-rc.7. Might want to give it some time to trickle through, but if you're up for giving it a go again that would be awesome. It will need a restart after upgrading, but it should be a lot less of a rocky ride than before.

**Comment by FichteFoll** [comment]
I'll see if I can try again on Friday. Won't be at a computer tomorrow.

**Comment by FichteFoll** [comment]
Not seeing any of these issues anymore 👍

**Comment by Slapbox** [comment]
I'm seeing this with `eslint_d` linter. Not sure if it's an issue with SublimeLinter or the linter plugin.

```
SublimeLinter: #583 eslint_d <untitled 533> ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\myUser\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\myUser\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 762, in lint
  File "lint.linter in C:\Users\myUser\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 1006, in run
  File "linter in C:\Users\myUser\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-eslint_d.sublime-package", line 78, in communicate
  File "./python3.3/ntpath.py", line 555, in relpath
ValueError: no path specified
```

**Comment by kaste** [comment]
eslint_d is unmaintained. Use eslint and set executable to eslint_d.

**Comment by Slapbox** [comment]
Thanks very much @kaste.

**Comment by Slapbox** [comment]
@kaste could you advise me on how to set the executable on the `eslint` plugin to use `eslint_d`? I'm finding SublimeLinter 4's configuration options to be very cryptic. I have the plugin installed, but I have no idea where to find the linter specific settings.

**Comment by FichteFoll** [comment]
http://www.sublimelinter.com/en/latest/linter_settings.html#executable

This should go into a linter's settings section in your User settings file.
