### ISSUE TITLE
Error when active view is image

### ISSUE THREAD

**Issue by gerardroche** [SublimeLinter/SublimeLinter3#731]
If the current view is an image then an error occurs on start.

To reproduce:

1. Open an image in a view.
2. Close ST
3. Open ST
4. Open the console to see traceback:

```
Traceback (most recent call last):
  File "/home/code/sublime_text_3/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "/home/code/.config/sublime-text-3/Packages/SublimeLinter/sublime_linter.py", line 64, in plugin_loaded
    plugin.on_activated_async(window.active_view())
  File "/home/code/.config/sublime-text-3/Packages/SublimeLinter/sublime_linter.py", line 97, in on_activated_async
    if util.is_scratch(view):
  File "/home/code/.config/sublime-text-3/Packages/SublimeLinter/lint/util.py", line 108, in is_scratch
    if view.is_scratch() or view.is_read_only() or not view.window() or view.settings().get("repl"):
AttributeError: 'NoneType' object has no attribute 'is_scratch'
```

Discovered via https://github.com/NeoVintageous/NeoVintageous/issues/297

**Comment by pykong** [comment]
@gerardroche, thanks for lettings us know. We are going to have a look into this.

**Comment by braver** [comment]
Should be gone now..
